// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitcoin_types.proto

/*
	Package bitcoin_types is a generated protocol buffer package.

	It is generated from these files:
		bitcoin_types.proto

	It has these top-level messages:
		BitcoinTransactionInput
		BitcoinTransactionOutput
		BitcoinTransactionType
*/
package bitcoin_types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// *
// Structure representing Bitcoin transaction input
type BitcoinTransactionInput struct {
	AddressN         *uint32 `protobuf:"varint,1,req,name=address_n,json=addressN" json:"address_n,omitempty"`
	PrevHash         []byte  `protobuf:"bytes,2,req,name=prev_hash,json=prevHash" json:"prev_hash,omitempty"`
	Index            *uint32 `protobuf:"varint,3,req,name=index" json:"index,omitempty"`
	Value            *uint64 `protobuf:"varint,4,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BitcoinTransactionInput) Reset()         { *m = BitcoinTransactionInput{} }
func (m *BitcoinTransactionInput) String() string { return proto.CompactTextString(m) }
func (*BitcoinTransactionInput) ProtoMessage()    {}
func (*BitcoinTransactionInput) Descriptor() ([]byte, []int) {
	return fileDescriptorBitcoinTypes, []int{0}
}

func (m *BitcoinTransactionInput) GetAddressN() uint32 {
	if m != nil && m.AddressN != nil {
		return *m.AddressN
	}
	return 0
}

func (m *BitcoinTransactionInput) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *BitcoinTransactionInput) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *BitcoinTransactionInput) GetValue() uint64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

// *
// Structure representing transaction output
type BitcoinTransactionOutput struct {
	Address          *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Coin             *uint64 `protobuf:"varint,2,req,name=coin" json:"coin,omitempty"`
	AddressIndex     *uint32 `protobuf:"varint,3,opt,name=address_index,json=addressIndex" json:"address_index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BitcoinTransactionOutput) Reset()         { *m = BitcoinTransactionOutput{} }
func (m *BitcoinTransactionOutput) String() string { return proto.CompactTextString(m) }
func (*BitcoinTransactionOutput) ProtoMessage()    {}
func (*BitcoinTransactionOutput) Descriptor() ([]byte, []int) {
	return fileDescriptorBitcoinTypes, []int{1}
}

func (m *BitcoinTransactionOutput) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *BitcoinTransactionOutput) GetCoin() uint64 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *BitcoinTransactionOutput) GetAddressIndex() uint32 {
	if m != nil && m.AddressIndex != nil {
		return *m.AddressIndex
	}
	return 0
}

// *
// Structure representing transaction
type BitcoinTransactionType struct {
	InputsCnt        *uint32                     `protobuf:"varint,2,opt,name=inputs_cnt,json=inputsCnt" json:"inputs_cnt,omitempty"`
	Inputs           []*BitcoinTransactionInput  `protobuf:"bytes,3,rep,name=inputs" json:"inputs,omitempty"`
	OutputsCnt       *uint32                     `protobuf:"varint,4,opt,name=outputs_cnt,json=outputsCnt" json:"outputs_cnt,omitempty"`
	Outputs          []*BitcoinTransactionOutput `protobuf:"bytes,5,rep,name=outputs" json:"outputs,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *BitcoinTransactionType) Reset()         { *m = BitcoinTransactionType{} }
func (m *BitcoinTransactionType) String() string { return proto.CompactTextString(m) }
func (*BitcoinTransactionType) ProtoMessage()    {}
func (*BitcoinTransactionType) Descriptor() ([]byte, []int) {
	return fileDescriptorBitcoinTypes, []int{2}
}

func (m *BitcoinTransactionType) GetInputsCnt() uint32 {
	if m != nil && m.InputsCnt != nil {
		return *m.InputsCnt
	}
	return 0
}

func (m *BitcoinTransactionType) GetInputs() []*BitcoinTransactionInput {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *BitcoinTransactionType) GetOutputsCnt() uint32 {
	if m != nil && m.OutputsCnt != nil {
		return *m.OutputsCnt
	}
	return 0
}

func (m *BitcoinTransactionType) GetOutputs() []*BitcoinTransactionOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func init() {
	proto.RegisterType((*BitcoinTransactionInput)(nil), "BitcoinTransactionInput")
	proto.RegisterType((*BitcoinTransactionOutput)(nil), "BitcoinTransactionOutput")
	proto.RegisterType((*BitcoinTransactionType)(nil), "BitcoinTransactionType")
}
func (m *BitcoinTransactionInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BitcoinTransactionInput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.AddressN == nil {
		return 0, proto.NewRequiredNotSetError("address_n")
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBitcoinTypes(dAtA, i, uint64(*m.AddressN))
	}
	if m.PrevHash == nil {
		return 0, proto.NewRequiredNotSetError("prev_hash")
	} else {
		dAtA[i] = 0x12
		i++
		i = encodeVarintBitcoinTypes(dAtA, i, uint64(len(m.PrevHash)))
		i += copy(dAtA[i:], m.PrevHash)
	}
	if m.Index == nil {
		return 0, proto.NewRequiredNotSetError("index")
	} else {
		dAtA[i] = 0x18
		i++
		i = encodeVarintBitcoinTypes(dAtA, i, uint64(*m.Index))
	}
	if m.Value == nil {
		return 0, proto.NewRequiredNotSetError("value")
	} else {
		dAtA[i] = 0x20
		i++
		i = encodeVarintBitcoinTypes(dAtA, i, uint64(*m.Value))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *BitcoinTransactionOutput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BitcoinTransactionOutput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Address == nil {
		return 0, proto.NewRequiredNotSetError("address")
	} else {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBitcoinTypes(dAtA, i, uint64(len(*m.Address)))
		i += copy(dAtA[i:], *m.Address)
	}
	if m.Coin == nil {
		return 0, proto.NewRequiredNotSetError("coin")
	} else {
		dAtA[i] = 0x10
		i++
		i = encodeVarintBitcoinTypes(dAtA, i, uint64(*m.Coin))
	}
	if m.AddressIndex != nil {
		dAtA[i] = 0x18
		i++
		i = encodeVarintBitcoinTypes(dAtA, i, uint64(*m.AddressIndex))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *BitcoinTransactionType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BitcoinTransactionType) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.InputsCnt != nil {
		dAtA[i] = 0x10
		i++
		i = encodeVarintBitcoinTypes(dAtA, i, uint64(*m.InputsCnt))
	}
	if len(m.Inputs) > 0 {
		for _, msg := range m.Inputs {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintBitcoinTypes(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.OutputsCnt != nil {
		dAtA[i] = 0x20
		i++
		i = encodeVarintBitcoinTypes(dAtA, i, uint64(*m.OutputsCnt))
	}
	if len(m.Outputs) > 0 {
		for _, msg := range m.Outputs {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintBitcoinTypes(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintBitcoinTypes(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *BitcoinTransactionInput) Size() (n int) {
	var l int
	_ = l
	if m.AddressN != nil {
		n += 1 + sovBitcoinTypes(uint64(*m.AddressN))
	}
	if m.PrevHash != nil {
		l = len(m.PrevHash)
		n += 1 + l + sovBitcoinTypes(uint64(l))
	}
	if m.Index != nil {
		n += 1 + sovBitcoinTypes(uint64(*m.Index))
	}
	if m.Value != nil {
		n += 1 + sovBitcoinTypes(uint64(*m.Value))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *BitcoinTransactionOutput) Size() (n int) {
	var l int
	_ = l
	if m.Address != nil {
		l = len(*m.Address)
		n += 1 + l + sovBitcoinTypes(uint64(l))
	}
	if m.Coin != nil {
		n += 1 + sovBitcoinTypes(uint64(*m.Coin))
	}
	if m.AddressIndex != nil {
		n += 1 + sovBitcoinTypes(uint64(*m.AddressIndex))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *BitcoinTransactionType) Size() (n int) {
	var l int
	_ = l
	if m.InputsCnt != nil {
		n += 1 + sovBitcoinTypes(uint64(*m.InputsCnt))
	}
	if len(m.Inputs) > 0 {
		for _, e := range m.Inputs {
			l = e.Size()
			n += 1 + l + sovBitcoinTypes(uint64(l))
		}
	}
	if m.OutputsCnt != nil {
		n += 1 + sovBitcoinTypes(uint64(*m.OutputsCnt))
	}
	if len(m.Outputs) > 0 {
		for _, e := range m.Outputs {
			l = e.Size()
			n += 1 + l + sovBitcoinTypes(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovBitcoinTypes(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozBitcoinTypes(x uint64) (n int) {
	return sovBitcoinTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BitcoinTransactionInput) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBitcoinTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BitcoinTransactionInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BitcoinTransactionInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressN", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AddressN = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBitcoinTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrevHash = append(m.PrevHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PrevHash == nil {
				m.PrevHash = []byte{}
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Index = &v
			hasFields[0] |= uint64(0x00000004)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Value = &v
			hasFields[0] |= uint64(0x00000008)
		default:
			iNdEx = preIndex
			skippy, err := skipBitcoinTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBitcoinTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return proto.NewRequiredNotSetError("address_n")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return proto.NewRequiredNotSetError("prev_hash")
	}
	if hasFields[0]&uint64(0x00000004) == 0 {
		return proto.NewRequiredNotSetError("index")
	}
	if hasFields[0]&uint64(0x00000008) == 0 {
		return proto.NewRequiredNotSetError("value")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BitcoinTransactionOutput) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBitcoinTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BitcoinTransactionOutput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BitcoinTransactionOutput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBitcoinTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Address = &s
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Coin = &v
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressIndex", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AddressIndex = &v
		default:
			iNdEx = preIndex
			skippy, err := skipBitcoinTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBitcoinTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return proto.NewRequiredNotSetError("address")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return proto.NewRequiredNotSetError("coin")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BitcoinTransactionType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBitcoinTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BitcoinTransactionType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BitcoinTransactionType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputsCnt", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.InputsCnt = &v
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBitcoinTypes
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Inputs = append(m.Inputs, &BitcoinTransactionInput{})
			if err := m.Inputs[len(m.Inputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputsCnt", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OutputsCnt = &v
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outputs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBitcoinTypes
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Outputs = append(m.Outputs, &BitcoinTransactionOutput{})
			if err := m.Outputs[len(m.Outputs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBitcoinTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBitcoinTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBitcoinTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBitcoinTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBitcoinTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthBitcoinTypes
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowBitcoinTypes
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipBitcoinTypes(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthBitcoinTypes = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBitcoinTypes   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("bitcoin_types.proto", fileDescriptorBitcoinTypes) }

var fileDescriptorBitcoinTypes = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x9a, 0xda, 0x76, 0xda, 0x40, 0x59, 0x45, 0x57, 0xc4, 0x1a, 0x2a, 0x48, 0x4e,
	0x41, 0xf4, 0x0d, 0xda, 0x8b, 0xf5, 0xa0, 0xb0, 0xf6, 0x1e, 0x36, 0x69, 0x24, 0x8b, 0xe9, 0x6e,
	0xc8, 0x6e, 0xaa, 0x7d, 0x00, 0x9f, 0xcb, 0xab, 0x47, 0x1f, 0x41, 0xfa, 0x24, 0xb2, 0xbb, 0x89,
	0x97, 0xd2, 0x5b, 0xfe, 0x2f, 0x33, 0xff, 0xfc, 0x33, 0x0b, 0xc7, 0x09, 0x53, 0xa9, 0x60, 0x3c,
	0x56, 0xdb, 0x32, 0x93, 0x51, 0x59, 0x09, 0x25, 0xa6, 0x9f, 0x0e, 0x9c, 0xcd, 0x2c, 0x5f, 0x56,
	0x94, 0x4b, 0x9a, 0x2a, 0x26, 0xf8, 0x82, 0x97, 0xb5, 0x42, 0x17, 0x30, 0xa0, 0xab, 0x55, 0x95,
	0x49, 0x19, 0x73, 0xec, 0x04, 0x6e, 0xe8, 0x93, 0x7e, 0x03, 0x9e, 0xf4, 0xcf, 0xb2, 0xca, 0x36,
	0x71, 0x4e, 0x65, 0x8e, 0xdd, 0xc0, 0x0d, 0x47, 0xa4, 0xaf, 0xc1, 0x03, 0x95, 0x39, 0x3a, 0x81,
	0x2e, 0xe3, 0xab, 0xec, 0x03, 0x77, 0x4c, 0x97, 0x15, 0x9a, 0x6e, 0x68, 0x51, 0x67, 0xd8, 0x0b,
	0xdc, 0xd0, 0x23, 0x56, 0x3c, 0x7a, 0xfd, 0xee, 0x78, 0x3c, 0x5d, 0x03, 0xde, 0x8f, 0xf1, 0x5c,
	0x2b, 0x9d, 0x03, 0x43, 0xaf, 0x19, 0x6b, 0x52, 0x0c, 0x48, 0x2b, 0x11, 0x02, 0x4f, 0xb7, 0x98,
	0xf9, 0x1e, 0x31, 0xdf, 0xe8, 0x1a, 0xfc, 0x36, 0x75, 0x9b, 0xc1, 0x09, 0x7d, 0x32, 0x6a, 0xe0,
	0x42, 0xb3, 0xe9, 0x97, 0x03, 0xa7, 0xfb, 0xf3, 0x96, 0xdb, 0x32, 0x43, 0x97, 0x00, 0x4c, 0xaf,
	0x2f, 0xe3, 0x94, 0x2b, 0xec, 0x9a, 0xe6, 0x81, 0x25, 0x73, 0xae, 0xd0, 0x2d, 0x1c, 0x59, 0x81,
	0x3b, 0x41, 0x27, 0x1c, 0xde, 0xe1, 0xe8, 0xc0, 0xf9, 0x48, 0x53, 0x87, 0xae, 0x60, 0x28, 0xcc,
	0x22, 0xd6, 0xd1, 0x33, 0x8e, 0xd0, 0x20, 0x6d, 0x79, 0x0f, 0xbd, 0x46, 0xe1, 0xae, 0xf1, 0x3c,
	0x8f, 0x0e, 0xdd, 0x82, 0xb4, 0x95, 0xb3, 0xf9, 0xf7, 0x6e, 0xe2, 0xfc, 0xec, 0x26, 0xce, 0xef,
	0x6e, 0xe2, 0xc0, 0x4d, 0x2a, 0xd6, 0x91, 0xa4, 0x4a, 0xc8, 0x9c, 0x15, 0x34, 0x91, 0xd1, 0xcb,
	0xdb, 0xf6, 0x9d, 0x16, 0x45, 0xa6, 0xa2, 0x82, 0x25, 0xf6, 0xad, 0x93, 0xfa, 0x75, 0xe6, 0xff,
	0x73, 0xbd, 0xeb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x70, 0x19, 0x02, 0x13, 0x02, 0x00,
	0x00,
}
