// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bitcoin_messages.proto

/*
	Package bitcoin_messages is a generated protocol buffer package.

	It is generated from these files:
		bitcoin_messages.proto

	It has these top-level messages:
		BitcoinAddress
		BitcoinTxAck
*/
package bitcoin_messages

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import bitcoin_types "."

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// *
// Request: Generate a Bitcoin address from a seed, device sends back the address in a Success message
// @next Failure
// @next ResponseBitcoinAddress
type BitcoinAddress struct {
	AddressN         *uint32 `protobuf:"varint,1,req,name=address_n,json=addressN" json:"address_n,omitempty"`
	StartIndex       *uint32 `protobuf:"varint,2,opt,name=start_index,json=startIndex" json:"start_index,omitempty"`
	ConfirmAddress   *bool   `protobuf:"varint,3,opt,name=confirm_address,json=confirmAddress" json:"confirm_address,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BitcoinAddress) Reset()                    { *m = BitcoinAddress{} }
func (m *BitcoinAddress) String() string            { return proto.CompactTextString(m) }
func (*BitcoinAddress) ProtoMessage()               {}
func (*BitcoinAddress) Descriptor() ([]byte, []int) { return fileDescriptorBitcoinMessages, []int{0} }

func (m *BitcoinAddress) GetAddressN() uint32 {
	if m != nil && m.AddressN != nil {
		return *m.AddressN
	}
	return 0
}

func (m *BitcoinAddress) GetStartIndex() uint32 {
	if m != nil && m.StartIndex != nil {
		return *m.StartIndex
	}
	return 0
}

func (m *BitcoinAddress) GetConfirmAddress() bool {
	if m != nil && m.ConfirmAddress != nil {
		return *m.ConfirmAddress
	}
	return false
}

// *
// Request: Send a part of data to Skywallet
// @next Failure
// @next TxRequest
type BitcoinTxAck struct {
	Tx               *bitcoin_types.BitcoinTransactionType `protobuf:"bytes,1,opt,name=tx" json:"tx,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *BitcoinTxAck) Reset()                    { *m = BitcoinTxAck{} }
func (m *BitcoinTxAck) String() string            { return proto.CompactTextString(m) }
func (*BitcoinTxAck) ProtoMessage()               {}
func (*BitcoinTxAck) Descriptor() ([]byte, []int) { return fileDescriptorBitcoinMessages, []int{1} }

func (m *BitcoinTxAck) GetTx() *bitcoin_types.BitcoinTransactionType {
	if m != nil {
		return m.Tx
	}
	return nil
}

func init() {
	proto.RegisterType((*BitcoinAddress)(nil), "BitcoinAddress")
	proto.RegisterType((*BitcoinTxAck)(nil), "BitcoinTxAck")
}
func (m *BitcoinAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BitcoinAddress) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.AddressN == nil {
		return 0, proto.NewRequiredNotSetError("address_n")
	} else {
		dAtA[i] = 0x8
		i++
		i = encodeVarintBitcoinMessages(dAtA, i, uint64(*m.AddressN))
	}
	if m.StartIndex != nil {
		dAtA[i] = 0x10
		i++
		i = encodeVarintBitcoinMessages(dAtA, i, uint64(*m.StartIndex))
	}
	if m.ConfirmAddress != nil {
		dAtA[i] = 0x18
		i++
		if *m.ConfirmAddress {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *BitcoinTxAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BitcoinTxAck) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Tx != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintBitcoinMessages(dAtA, i, uint64(m.Tx.Size()))
		n1, err := m.Tx.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintBitcoinMessages(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *BitcoinAddress) Size() (n int) {
	var l int
	_ = l
	if m.AddressN != nil {
		n += 1 + sovBitcoinMessages(uint64(*m.AddressN))
	}
	if m.StartIndex != nil {
		n += 1 + sovBitcoinMessages(uint64(*m.StartIndex))
	}
	if m.ConfirmAddress != nil {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *BitcoinTxAck) Size() (n int) {
	var l int
	_ = l
	if m.Tx != nil {
		l = m.Tx.Size()
		n += 1 + l + sovBitcoinMessages(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovBitcoinMessages(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozBitcoinMessages(x uint64) (n int) {
	return sovBitcoinMessages(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BitcoinAddress) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBitcoinMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BitcoinAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BitcoinAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressN", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AddressN = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartIndex", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StartIndex = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfirmAddress", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.ConfirmAddress = &b
		default:
			iNdEx = preIndex
			skippy, err := skipBitcoinMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBitcoinMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return proto.NewRequiredNotSetError("address_n")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BitcoinTxAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBitcoinMessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BitcoinTxAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BitcoinTxAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinMessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBitcoinMessages
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tx == nil {
				m.Tx = &bitcoin_types.BitcoinTransactionType{}
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBitcoinMessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBitcoinMessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBitcoinMessages(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBitcoinMessages
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBitcoinMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBitcoinMessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthBitcoinMessages
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowBitcoinMessages
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipBitcoinMessages(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthBitcoinMessages = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBitcoinMessages   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("bitcoin_messages.proto", fileDescriptorBitcoinMessages) }

var fileDescriptorBitcoinMessages = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcf, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0x60, 0x39, 0x74, 0x48, 0x5d, 0x52, 0x50, 0x90, 0x20, 0x02, 0x29, 0x44, 0x1d, 0x68,
	0x26, 0x0f, 0x2c, 0xcc, 0x0d, 0x13, 0x0c, 0x0c, 0xa1, 0x7b, 0xe4, 0x38, 0x2e, 0x58, 0x4d, 0xec,
	0xc8, 0x77, 0x88, 0x64, 0xe0, 0xfd, 0x18, 0x79, 0x04, 0x94, 0x27, 0x41, 0x25, 0x4e, 0xb7, 0xd3,
	0x77, 0xba, 0xfb, 0xf5, 0xd3, 0xcb, 0x52, 0xa1, 0x30, 0x4a, 0x17, 0x8d, 0x04, 0xe0, 0x6f, 0x12,
	0x58, 0x6b, 0x0d, 0x9a, 0xeb, 0x8b, 0xc9, 0xb1, 0x6f, 0x27, 0x5c, 0x7d, 0xd1, 0x65, 0x36, 0xf2,
	0xa6, 0xaa, 0xac, 0x04, 0x08, 0x6f, 0xe8, 0x9c, 0x8f, 0x63, 0xa1, 0x23, 0x92, 0x78, 0x69, 0x90,
	0xfb, 0x0e, 0x5e, 0xc2, 0x5b, 0xba, 0x00, 0xe4, 0x16, 0x0b, 0xa5, 0x2b, 0xd9, 0x45, 0x5e, 0x42,
	0xd2, 0x20, 0xa7, 0xff, 0xf4, 0x74, 0x90, 0x70, 0x4d, 0xcf, 0x84, 0xd1, 0x3b, 0x65, 0x9b, 0xc2,
	0x1d, 0x45, 0x27, 0x09, 0x49, 0xfd, 0x7c, 0xe9, 0xd8, 0xc5, 0x3c, 0xcf, 0xfc, 0xd9, 0xf9, 0x7c,
	0xf5, 0x40, 0x4f, 0x5d, 0xfc, 0xb6, 0xdb, 0x88, 0x7d, 0xb8, 0xa6, 0x1e, 0x76, 0x11, 0x49, 0x48,
	0xba, 0xb8, 0xbf, 0x62, 0xd3, 0xca, 0x72, 0x0d, 0x5c, 0xa0, 0x32, 0x7a, 0xdb, 0xb7, 0x32, 0xf7,
	0xb0, 0xcb, 0x1e, 0xbf, 0x87, 0x98, 0xfc, 0x0c, 0x31, 0xf9, 0x1d, 0x62, 0x42, 0xef, 0x84, 0x69,
	0x18, 0x70, 0x34, 0xf0, 0xae, 0x6a, 0x5e, 0x02, 0x7b, 0xdd, 0xf7, 0x9f, 0xbc, 0xae, 0x25, 0xb2,
	0x5a, 0x95, 0x63, 0xd5, 0xf2, 0x63, 0x97, 0x05, 0x47, 0x3f, 0x3c, 0xfa, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0xae, 0xb6, 0xae, 0xac, 0x2a, 0x01, 0x00, 0x00,
}
